# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 1.0745e-38],
        [1.0653e-38, 1.0286e-38, 1.0194e-38]])


In [8]:
import numpy as np

In [6]:
x.shape[1]

3

Construct a randomly initialized matrix

In [13]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5296, 0.1249, 0.1160],
        [0.3635, 0.2526, 0.0962],
        [0.3143, 0.3819, 0.4967],
        [0.4580, 0.0992, 0.0203],
        [0.9118, 0.1681, 0.2022]])


Get its size

In [14]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [15]:
x[1:3] = 2
print(x)

tensor([[0.5296, 0.1249, 0.1160],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.4580, 0.0992, 0.0203],
        [0.9118, 0.1681, 0.2022]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [19]:
new = torch.Tensor(2,17)
print(new)

tensor([[-6.6521e+28,  5.6612e-43, -6.6985e+28,  5.6612e-43, -6.7002e+28,
          5.6612e-43, -6.6994e+28,  5.6612e-43, -6.7000e+28,  5.6612e-43,
         -6.7001e+28,  5.6612e-43, -6.6998e+28,  5.6612e-43, -6.6986e+28,
          5.6612e-43, -6.6986e+28],
        [ 5.6612e-43, -6.6987e+28,  5.6612e-43, -6.6988e+28,  5.6612e-43,
         -6.6985e+28,  5.6612e-43, -6.6990e+28,  5.6612e-43, -6.6988e+28,
          5.6612e-43, -6.6998e+28,  5.6612e-43, -6.6989e+28,  5.6612e-43,
         -6.6989e+28,  5.6612e-43]])


In [21]:
new = torch.FloatTensor(3,1)
print(new)

tensor([[1.4013e-45],
        [0.0000e+00],
        [0.0000e+00]])


In [26]:
new = torch.LongTensor(5,2,1)
new[:,:] = 7
print(new)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [55]:
new = torch.ByteTensor(5,)
new[1:4] = 1

print(new)

tensor([121,   1,   1,   1, 104], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [68]:
x = torch.FloatTensor(5,3)
x[:,0] = 10
x[:,1] = 20
x[:,2] = 30

In [69]:
x

tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])

In [70]:
y = torch.rand(5, 3)
print(x + y)

tensor([[10.5958, 20.7519, 30.1037],
        [10.0370, 20.3222, 30.8369],
        [10.8187, 20.6893, 30.9981],
        [10.2136, 20.0090, 30.5762],
        [10.2709, 20.4038, 30.8797]])


### 2.2 Addition: syntax 2

In [71]:
print(torch.add(x, y))

tensor([[10.5958, 20.7519, 30.1037],
        [10.0370, 20.3222, 30.8369],
        [10.8187, 20.6893, 30.9981],
        [10.2136, 20.0090, 30.5762],
        [10.2709, 20.4038, 30.8797]])


### 2.3 Addition: giving an output tensor

In [74]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[20.5958, 40.7519, 60.1037],
        [20.0370, 40.3222, 60.8369],
        [20.8187, 40.6893, 60.9981],
        [20.2136, 40.0090, 60.5762],
        [20.2709, 40.4038, 60.8797]])


### 2.4 Addition: in-place

adds `x`to `y`

In [73]:
y.add_(x)
print(y)

tensor([[10.5958, 20.7519, 30.1037],
        [10.0370, 20.3222, 30.8369],
        [10.8187, 20.6893, 30.9981],
        [10.2136, 20.0090, 30.5762],
        [10.2709, 20.4038, 30.8797]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [75]:
print(x[:, 1])

tensor([20., 20., 20., 20., 20.])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [79]:
a = torch.FloatTensor(2,4)
a[:,:] = 10
b = torch.FloatTensor(2,4)
b[:,:] = 30

In [80]:
a

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [81]:
b

tensor([[30., 30., 30., 30.],
        [30., 30., 30., 30.]])

In [84]:
new = a*b

new = torch.multiply(a,b)
print(new)

tensor([[300., 300., 300., 300.],
        [300., 300., 300., 300.]])


In [86]:
torch.multiply(a,b, out=result)
print(result)

tensor([[300., 300., 300., 300.],
        [300., 300., 300., 300.]])


<ipython-input-86-82b67930d270>:1: UserWarning: An output with one or more elements was resized since it had shape [5, 3], which does not match the required output shape [2, 4].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ..\aten\src\ATen\native\Resize.cpp:23.)
  torch.multiply(a,b, out=result)


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [ ]:
a = torch.ones(5)
print(a)

In [ ]:
b = a.numpy()
print(b)

See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [ ]:
a.add_(1)
print(a)
print(b)

### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")